import type { Metadata } from "next";
import { Outfit, Playfair_Display } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/ConditionalNavbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/Footer";
import HotelReg from "@/components/HotelReg";
import AppContextProvider from "@/context/AppContext";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AppContextProvider>
        <html lang="en">
          <body className={`${outfit.variable} ${playfair.variable} font-sans antialiased`}>
            <Toaster />
            <ConditionalNavbar />
            {false && <HotelReg />}

            <div className="min-h-[70vh]">
              {children}
            </div>

            <Footer />
          </body>
        </html>
      </AppContextProvider>
    </ClerkProvider>
  );
}
